image: docker:latest

image: docker:latest

pipelines:
  pull-requests:
    branches:
      develop:
        - step:
            name: Build and run containers
            services:
              - docker
            script:
              - echo "Running tests on pull request"
              #- export DOCKER_BUILDKIT=0
              #- export XDEBUG_MODE=${XDEBUG_MODE:-off}
              #- docker-compose --env-file .env.local -f docker-compose.yaml -f docker-compose.dev.yaml up -d --build
            caches:
              - docker
definitions:
  services:
    docker:
      memory: 3072