services:
    # nginx
    web:
        build:
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${APP_PORT}:80"
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: "${BUILD_TARGET:-app}"
        volumes:
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            DATABASE_URL: ${DATABASE_URL}
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    # redis
    cache:
        image: redis:latest

volumes:
    mysql-data:
